### PR TITLE
cassandra-reaper

### PR DESCRIPTION
**Pull request by developer-guy**
- https://github.com/wolfi-dev/os/pull/10893

/cc @Dentrax

### CODE REVIEW

File: cassandra-reaper.advisories.yaml [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+          note: To be able to fix this CVE, we need to upgrade the "org.apache.cassandra:cassandra-all" dependency version from `2.2.12` which is the version project is currently using to at least `4.0.10` which is the version we should bump to to fix the CVEs but we can't because the build was failed due to compilation errors.
+
+  - id: CVE-2020-8908
+    aliases:
+      - GHSA-5mg8-w23w-74h3
+    events:
+      - timestamp: 2024-01-11T09:54:49Z
+        type: pending-upstream-fix
+        data:
+          note: Pending upstream fix, this fix will require some code changes since when we upgrade the "com.google.guava:guava" dependency version from `24.1.1-jre` which is the version project is currently using to `32.0.0-android` which is the version we should bump to to fix the CVEs but we can't because the build was failed due to compilation errors.
```
Comment (stormqueen1990) [inline cassandra-reaper.advisories.yaml:23]: Perhaps we can just mention the version here without the variant?

```suggestion
          note: Pending upstream fix, this fix will require some code changes since when we upgrade the "com.google.guava:guava" dependency version from 24.1.1 which is the version project is currently using to 32.0.0 which is the version we should bump to to fix the CVEs but we can't because the build was failed due to compilation errors.
```

File: cassandra-reaper.advisories.yaml [hunk 2]
```diff
@@ -0,0 +1,32 @@
...
+
+  - id: CVE-2023-2976
+    aliases:
+      - GHSA-7g45-4rm6-3mm3
+    events:
+      - timestamp: 2024-01-11T09:59:33Z
+        type: pending-upstream-fix
+        data:
+          note: Pending upstream fix, this fix will require some code changes since when we upgrade the "com.google.guava:guava" dependency version from `24.1.1-jre` which is the version project is currently using to `32.0.0-android` which is the version we should upgrade to fix the CVEs but we can't because the build was failed due to compilation errors.
```
Comment (stormqueen1990) [inline cassandra-reaper.advisories.yaml:32]:
```suggestion
          note: Pending upstream fix, this fix will require some code changes since when we upgrade the "com.google.guava:guava" dependency version from 24.1.1 which is the version project is currently using to 32.0.0 which is the version we should upgrade to fix the CVEs but we can't because the build was failed due to compilation errors.
```

**Review by stormqueen1990 — COMMENTED** [review]
LGTM!

**Comment by luhring** [comment]
Should only need a rebase and current timestamps on the new entries, and this looks good to go!

**Review by luhring — APPROVED** [review]

**Review by luhring — APPROVED** [review]
@developer-guy thanks for your patience on this one!
